# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GroceryHelper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GroceryHelper
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database',inhibit_warnings => true
  target 'GroceryHelperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GroceryHelperUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
