# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GroceryHelper2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GroceryHelper2
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'GroceryHelper2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GroceryHelper2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
